AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ImageUri: { Type: String }
  LambdaRoleArn: { Type: String }
  ProjectTag: { Type: String }
  OwnerTag: { Type: String }
  EnvTag: { Type: String }
  SystemState: { Type: String }

Resources:

  ChatFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role: !Ref LambdaRoleArn
      Code:
        ImageUri: !Ref ImageUri
      Environment:
        Variables:
          SYSTEM_STATE: !Ref SystemState
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: Environment
          Value: !Ref EnvTag

  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt ChatFunction.Arn
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"

  LambdaUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ChatFunction.Arn
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  FunctionUrl:
    Value: !GetAtt LambdaFunctionUrl.FunctionUrl