AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ImageUri: { Type: String }
  LambdaRoleArn: { Type: String }
  ProjectTag: { Type: String }
  OwnerTag: { Type: String }
  EnvTag: { Type: String }
  SystemState: { Type: String }

Resources:

  ChatFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role: !Ref LambdaRoleArn
      Code:
        ImageUri: !Ref ImageUri
      Environment:
        Variables:
          SYSTEM_STATE: !Ref SystemState
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: Environment
          Value: !Ref EnvTag
