AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ChatImageUri: { Type: String }
  IngestionImageUri: { Type: String }
  LambdaRoleArn: { Type: String }
  ProjectTag: { Type: String }
  OwnerTag: { Type: String }
  EnvTag: { Type: String }
  SystemState: { Type: String }

Resources:

  ChatFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role: !Ref LambdaRoleArn
      Code:
        ImageUri: !Ref ChatImageUri
      Timeout: 60
      Environment:
        Variables:
          SYSTEM_STATE: !Ref SystemState
          DOCUMENTS_BUCKET: !Sub "bedrock-rag-documents-${AWS::AccountId}"
          VECTORS_BUCKET: !Sub "bedrock-rag-vectors-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: Environment
          Value: !Ref EnvTag
        - Key: Component
          Value: chat
        - Key: CostCenter
          Value: personal-project

  IngestionFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role: !Ref LambdaRoleArn
      Code:
        ImageUri: !Ref IngestionImageUri
      Timeout: 300
      Environment:
        Variables:
          DOCUMENTS_BUCKET: !Sub "bedrock-rag-documents-${AWS::AccountId}"
          VECTORS_BUCKET: !Sub "bedrock-rag-vectors-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: Environment
          Value: !Ref EnvTag
        - Key: Component
          Value: ingestion
        - Key: CostCenter
          Value: personal-project

  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt ChatFunction.Arn
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"

  LambdaUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ChatFunction.Arn
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ChatFunction.Arn
      Action: lambda:InvokeFunction
      Principal: "*"

  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt IngestionFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::bedrock-rag-documents-${AWS::AccountId}"

Outputs:
  FunctionUrl:
    Value: !GetAtt LambdaFunctionUrl.FunctionUrl
  IngestionFunctionArn:
    Value: !GetAtt IngestionFunction.Arn