AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda execution role

Parameters:
  ProjectTag:
    Type: String
  OwnerTag:
    Type: String
  EnvTag:
    Type: String

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bedrock-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: bedrock-lambda-policy
      Roles:
        - !Ref LambdaRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - aws-marketplace:ViewSubscriptions
              - aws-marketplace:Subscribe
              - aws-marketplace:Unsubscribe
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource:
              - !Sub "arn:aws:s3:::bedrock-rag-documents-${AWS::AccountId}"
              - !Sub "arn:aws:s3:::bedrock-rag-documents-${AWS::AccountId}/*"
          - Effect: Allow
            Action:
              - textract:StartDocumentTextDetection
              - textract:GetDocumentTextDetection
            Resource: "*"

Outputs:
  LambdaRoleArn:
    Value: !GetAtt LambdaRole.Arn